[Config]
# Whether or not to add a local dns entry if it's needed to connect to the server with the official domain.
# Including to avoid receiving that it's on maintenance.
# If using '{HostFilePath}' in 'Client.ExecutableArgs', this will be ignored.
# Note: Will require admin privileges.
CanAddHost = true
# Whether or not to trust the certificate of the server in user or local store, or not at all.
# false: do not trust the certificate. You will have to trust it manually in the proper store before running the launcher.
# local: trust the certificate in the local store. Requires admin rights.
# user: trust the certificate in the user store. Requires user consent. Only on Windows.
# If using '{CertFilePath}' in 'Client.ExecutableArgs', this will be ignored.
CanTrustCertificate = 'local'
# Whether or not to broadcast the game BattleServer to all interfaces in LAN (not just the most priority one).
# Either 'auto' or 'false'. This is only necessary in Windows when not running AoM, on the rest of systems it is always 'false'.
CanBroadcastBattleServer = 'auto'
# If true, the launcher will isolate the metadata cache of the game, if false, it will be shared
# On AoE I this is always false as it does not store metadata.
# Linux Note: Only supported when not using a custom launcher.
IsolateMetadata = true
# (Experimental) If true, the launcher will isolate the user profiles of the game, if false, it will be shared.
# May cause issues with Steam Cloud or Xbox Cloud (depending on the game version).
# Linux Note: Only supported when not using a custom launcher.
IsolateProfiles = false

[Server]
# Whether to start the server automatically or 'auto', which will start the server is no server is found in the LAN
# 'auto' depend on the Announce setting in the server config being true to find servers.
Start = 'auto'
# The process to start the server, if 'auto', it will be try to execute the server binary in this directory order:
# 1. './server/'
# 2. '../server/'
# 3. '../../server/'
# Note: You may use environment variables.
Executable = 'auto'
# The arguments to pass to the server executable if starting it. Execute the server help flag for available arguments.
# {Game} will be replaced by the game name. Default, only start the server for the given name.
# {Id} will be replaced by a random unique server id (UUID v4).
# Windows: Path names need to use double backslashes within single quotes or be within double quotes.
# Note: You may use environment variables.
ExecutableArgs = ['-e', '{Game}', '--id', '{Id}']
# The host of the server to connect to if Start = false, if Start = true/auto this will be ignored
# The host may be a DNS name or Ipv4 IP. 0.0.0.0 means every local interface IP.
# Note: See the server config to set the interface to bind to.
Host = '0.0.0.0'
# Whether to stop it automatically, if 'auto', it will stop the server if Start = true (or 'auto' does not find a server)
# This will also stop the Battle Server is one was started with the Battle Server Manager.
Stop = 'auto'
# Announce ports to listen to. If not including the default port, default configured servers will not get discovered.
AnnouncePorts = [31978]
# Announce multicast group adresses to join.
# If not including the default group, default configured servers will not get discovered via Multicast.
# Only IPv4 is supported.
AnnounceMulticastGroups = ['239.31.97.8']

# This section only applies if starting the server.
[Server.BattleServerManager]
# When to use the manager to start a new Battle Server running the manager; accepted values:
# 'required': Only for games that require it to work (AoM: RT).
# 'true'.
# 'false'.
# Note: by default the manager will only start a new instance if one is not already running for the given game.
Run = 'true'
# The process to start the battle-server-manager,
# if 'auto', it will be try to execute the server binary in this directory order:
# 1. './battle-server-manager/'
# 2. '../'
# 3. '../battle-server-manager/'
# Note: You may use environment variables.
Executable = 'auto'
# The arguments to pass to the Battle Server Manager executable if starting it.
# Execute the manager help flag for available arguments.
# {Game} will be replaced by the game name.
# By default, it will also hide the BattleServer.exe window (apart from the manager itself).
# Note: You may use environment variables.
ExecutableArgs = ['-e', '{Game}', '-r']
