# Whether to log all the info the terminal plus more info to a file. Enable it for errors.
Log = false

# Whether to generate the Platform User Id. *ONLY* as a last resort if multiple users
# are using Custom Launchers and they are sharing incorrectly the same Platform User Id.
GeneratePlatformUserId = false

[Games]
# Games that the server will accept.
# "age1" (AoE: DE), "age2" (AoE II: DE), "age3" (AoE III: DE) and "athens" (AoM: RT).
Enabled = []

# Games.<game>.Hosts is the hosts/IPs the server will bind to for that game. Only IPv4 is supported.
# Must be *unique* within enabled games.
# *Recommended to change to the LAN host* (use 0.0.0.0 and 127.0.0.1 for testing)

[Games.age1]
Hosts = ['0.0.0.0']

[Games.age2]
Hosts = ['0.0.0.0']

[Games.age3]
Hosts = ['0.0.0.0']

[Games.athens]
Hosts = ['0.0.0.0']

# CONFIGURING BATTLE SERVERS
# See the complete information in BattleServers.md
[Announcement]

# Whether to respond discovery queries in LAN. When disabled, the launcher will not automatically detect it.
Enabled = true
# Whether to respond discovery queries in the Multicast address.
Multicast = true
# Port to announce to. If changed, the launchers will need to specify the port in Server.AnnouncePorts
Port = 31978
# Multicast group to respond to (IPv4 only).
# If changed, the launchers will need to specify the address in Server.AnnounceMulticastGroups.
MulticastGroup = '239.31.97.8'
