# The hosts/IPs the server will bind to. Only Ipv4 is supported.
# *Recommended to change to the LAN host* (use 0.0.0.0 and 127.0.0.1 for testing)
Hosts = ['0.0.0.0']

# Whether to log the requests to the console (stdout) or not (files)
LogToConsole = false

# Whether to generate the Platform User Id based on the user's IP. *ONLY* recommended if using two or more users
# are using Custom Launchers and they are sharing incorrectly the same Platform User Id.
GeneratePlatformUserId = false

# Games that the server will accept. "age1" (AoE DE), "age2" (AoE II DE) and "age3" (AoE III DE) are supported.
Games = ['age1', 'age2', 'age3']

[Announcement]

# Whether to announce the server. When disabled, the launcher will not automatically detect it.
Enabled = true
# Whether to announce the server using Multicast. More efficient but less compatible than Broadcast.
Multicast = true
# Whether to announce the server using Broadcast.
Broadcast = true
# Port to announce to. If changed, the launchers will need to specify the port in Server.AnnouncePorts
Port = 31978
# Multicast group to announce to (IPv4 only).
# If changed, the launchers will need to specify the address in Server.AnnounceMulticastGroups to receive multicasts.
MulticastGroup = '239.31.97.8'
